name: Build & Deploy Next.js to Azure Web App (Linux)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout full repo (all folders)
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Setup Node
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      # 3. Install dependencies
      - name: Install deps (CI)
        run: npm ci

      # 4. Build Next.js
      - name: Build Next.js
        run: npm run build

      # (Optional) prune devDependencies if you want smaller deploy
      # - name: Prune to production deps
      #   run: npm prune --production

      # 5. Deploy entire repo (all folders) to Azure
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'seqfirstweb' # replace with your Azure Web App name
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .
